// GENERATED by scripts/zoho/gen-base-schema.mjs — do not edit by hand.
export interface TableRef {
  name: string
  id: string
  appId: string
  dataJson?: string
  fields: Record<string, string>
}

export const BASE_ID = "dhorj90a2ded0152a4f1d94ae8ce4ece09a5c"

export const T: Record<string, TableRef> = {
  "Vendor Types": {"name":"Vendor Types","id":"J8fAew","appId":"bIdD3Q","dataJson":"fihkzA","fields":{"Name":"mWDsTw","Source Kind":"d_SISg","Description":"OkAsRQ","Status":"e7N1Eg","Link to Vendors":"MHiaiA","App ID":"bIdD3Q","Data JSON":"fihkzA"}},
  "Vendors": {"name":"Vendors","id":"S6mCPQ","appId":"N7M87g","dataJson":"mUCm1A","fields":{"Name":"RsrjJQ","Phone":"IgaF2w","Area":"cTKTpQ","Payment Terms":"EuI4aQ","Status":"6Hsqrw","Email":"r1YVmw","Notes":"LSi-4Q","Vendor Type":"1HpEPw","Link to Purchase Products":"wMDCTA","Link to GRNs":"lGwzHQ","App ID":"N7M87g","Data JSON":"mUCm1A"}},
  "Customers": {"name":"Customers","id":"Eyis7A","appId":"tVfd2w","dataJson":"d35BZw","fields":{"Name":"7Qkpvw","Ship To":"x3HFGg","GSTIN":"7hEZzA","Status":"qwdKoQ","Phone":"RGmwRg","Email":"xCjjeQ","Contact Person":"_gxAqA","Notes":"rpWUBQ","Link to Lab Reports":"6cfsXA","Link to Orders":"y3Fdkw","Link to Dispatches":"iUaqVw","App ID":"tVfd2w","Data JSON":"d35BZw"}},
  "Items": {"name":"Items","id":"wbQrEQ","appId":"e_VT0Q","dataJson":"1mu_wg","fields":{"Name":"PpoqtQ","Type":"_BKnWg","UOM":"jd1Myg","Lot Controlled":"IyDQmA","Reorder Level":"SSAZ2Q","Cost Method":"9aOsEw","Link to Purchase Products":"p2moVQ","Link to Products":"p3tJkQ","Link to BOM Lines":"iYDDEA","Link to Melanges":"bMEblg","Link to Melange Components":"E4Em1Q","Link to Packing Runs":"rT3QHg","Link to QC Records":"NDfAlg","Link to Ledger":"B7WnUw","App ID":"e_VT0Q","Data JSON":"1mu_wg"}},
  "Purchase Products": {"name":"Purchase Products","id":"5ni6OA","appId":"Mr__lw","dataJson":"Txb5eQ","fields":{"Name":"3AD6-w","Default UOM":"MJ16Tg","Item":"3KSmNA","Linked Vendors":"3vPnXw","Link to GRNs":"x0DXcg","App ID":"Mr__lw","Data JSON":"Txb5eQ"}},
  "Storage Locations": {"name":"Storage Locations","id":"YqOCjA","appId":"2PW1fg","dataJson":"n4PyuA","fields":{"Name":"sNsFpA","Label":"-9Xw5w","Holds":"TrEehw","Type":"rSm5Vw","Status":"ro-7oQ","Link to GRNs":"mfg58A","Link to Batches":"iXliRQ","Link to Packing Runs":"GNeEOQ","Link to Dispatches":"0oJhUg","Link to Ledger":"hJeLgw","App ID":"2PW1fg","Data JSON":"n4PyuA"}},
  "Test Categories": {"name":"Test Categories","id":"VBvfXw","appId":"LeWJaQ","dataJson":"o0EOqA","fields":{"Title":"9tEHrw","Format":"Z7-yYg","Required for Release":"LJEe3A","Pass Score":"hr_xWg","Minor Score":"mzLgEQ","Signatory":"DtjfHA","Status":"YDOSNQ","Link to Test Parameters":"MuNBCg","Link to Lab Reports":"vcCk9w","App ID":"LeWJaQ","Data JSON":"o0EOqA"}},
  "Test Parameters": {"name":"Test Parameters","id":"QPV8cw","appId":"tsbi5g","dataJson":"jFBY_w","fields":{"Name":"p8lUhw","Method":"36Xc5g","Unit":"vPgdgg","Category":"nhKxWA","App ID":"tsbi5g","Data JSON":"jFBY_w"}},
  "Products": {"name":"Products","id":"ffFn3w","appId":"h00iuA","dataJson":"YPalvg","fields":{"Name":"V8DP7g","Format":"-mYvFg","Size":"UBqqrg","Unit":"3l8bdQ","Pack Volume":"YbK3lw","Shelf Life Days":"aM43FQ","Chilled Shelf Life Days":"usFooQ","MRP":"mnFdTw","Medium":"KwUYQA","Bulk Item":"zduh7g","Link to BOM Lines":"TYwAAQ","Link to Order Lines":"oYLG6w","Link to Dispatches":"HGqyYQ","App ID":"h00iuA","Data JSON":"YPalvg"}},
  "BOM Lines": {"name":"BOM Lines","id":"jfdh2w","appId":"utmcmA","dataJson":"GRpj0A","fields":{"Line":"zfIZOg","Qty per Pack":"R-4XNA","Product":"4e3BDg","Item":"_RE51w","App ID":"utmcmA","Data JSON":"GRpj0A"}},
  "Melanges": {"name":"Melanges","id":"9ZBRBg","appId":"TxUAlA","dataJson":"NZs2pg","fields":{"Name":"MeS7ZQ","Status":"BcLplw","Output Item":"8y49VA","Link to Melange Components":"7n8WDg","App ID":"TxUAlA","Data JSON":"NZs2pg"}},
  "Melange Components": {"name":"Melange Components","id":"2Yw3aw","appId":"YdSfiQ","dataJson":"W53o6A","fields":{"Line":"7ZKMiA","Share":"S5-StQ","Melange":"78C4JA","Item":"NpgT1A","App ID":"YdSfiQ","Data JSON":"W53o6A"}},
  "Counters": {"name":"Counters","id":"1l4Zyg","appId":"a4d7zA","fields":{"Series":"LsDPPA","Prefix":"pRhS8w","Pattern":"qP8tHA","Pad":"U8SH4g","Next":"FXa_pg","App ID":"a4d7zA"}},
  "Config": {"name":"Config","id":"_GPmew","appId":"zvpKQQ","fields":{"Setting":"gPjX7g","Value":"8KlOrg","Notes":"4ZYVyg","App ID":"zvpKQQ"}},
  "Staff": {"name":"Staff","id":"NhIr-w","appId":"1Y0FkQ","dataJson":"0UaM3g","fields":{"Staff No":"rOE8TQ","Name":"I9iRyA","Role":"iW0apg","Phone":"cKLfnQ","Status":"pwzEcw","Added On":"IYA94A","Link to Shifts":"6EtwEw","Link to Attendance":"4UdTuA","App ID":"1Y0FkQ","Data JSON":"0UaM3g"}},
  "GRNs": {"name":"GRNs","id":"JWefYw","appId":"UnjJ3Q","dataJson":"yJdqrA","fields":{"Doc No":"sS7eYg","Date":"xa31Mw","UOM":"H5waRg","Area":"uRMmeA","Harvested On":"HrjCTA","Total":"LoCJ-g","Accepted":"WKnwyg","Free":"ZOcdSg","Grade A":"lEAVZg","Grade B":"rYt5fA","Grade C":"PEMOXQ","Reject":"SrFo5A","Rate":"MSb-kQ","Other Charges":"dqpepw","Status":"KACfAA","Notes":"XG_gxA","Product":"vSiTJA","Location":"BBTg8g","Vendor":"Yiy0mA","App ID":"UnjJ3Q","Data JSON":"yJdqrA"}},
  "Batches": {"name":"Batches","id":"5ZkZOA","appId":"EqZmyA","dataJson":"ppf_Uw","fields":{"Batch No":"hlXcIg","Date":"_HXteA","Kind":"NMSTZw","Spoiled":"cjtEPQ","Cost per Unit":"qJi6Tg","Status":"afpPHA","Data JSON":"ppf_Uw","Location":"DhG6mw","Link to Packing Runs":"2V6Isw","Link to QC Records":"5Ee8ZA","Link to Lab Reports":"L4tueQ","Link to Dispatches":"Z6bnCw","App ID":"EqZmyA"}},
  "Packing Runs": {"name":"Packing Runs","id":"aK0RyA","appId":"zYkg9A","dataJson":"r6uyyw","fields":{"Run No":"Nk6ucQ","Date":"FjAHyA","Drawn":"vV24Jg","Status":"M8eM0g","Data JSON":"r6uyyw","Batch":"XjQsbA","Bulk Item":"Q7WamQ","Location":"cvK-qQ","App ID":"zYkg9A"}},
  "QC Records": {"name":"QC Records","id":"FtR93w","appId":"2SFmmQ","dataJson":"IIcgIA","fields":{"Doc No":"qWOqhg","Disposition":"Tp2XxQ","Tests JSON":"dB6PSQ","Attachments":"tlwO8Q","Batch":"ZOJ5Xw","Item":"ULT4qg","App ID":"2SFmmQ","Data JSON":"IIcgIA"}},
  "Lab Reports": {"name":"Lab Reports","id":"1sbYJA","appId":"a2nt6g","dataJson":"Vg6SxA","fields":{"Report No":"XohvDA","Sample Date":"aO_TOQ","Issue Date":"PHqUGw","Scores JSON":"8OpJnw","Decision":"5uLRRA","Attachment":"o9TXJA","Category":"U9aWfw","Batch":"DkZjdg","Customer":"Zo7ggg","App ID":"a2nt6g","Data JSON":"Vg6SxA"}},
  "Orders": {"name":"Orders","id":"-VGCAQ","appId":"kxYh8A","dataJson":"bBMaAQ","fields":{"Order No":"GenTxA","Date":"sJeFlA","Status":"psg9zw","Notes":"Y3YO0A","Customer":"enRipQ","Link to Order Lines":"jgFx5w","App ID":"kxYh8A","Data JSON":"bBMaAQ"}},
  "Order Lines": {"name":"Order Lines","id":"XF04qg","appId":"9Q8vcw","dataJson":"YEd52A","fields":{"Line":"6NlSpg","Qty":"zusIbQ","Order":"fH6cVg","SKU":"aevB4w","App ID":"9Q8vcw","Data JSON":"YEd52A"}},
  "Dispatches": {"name":"Dispatches","id":"tranOA","appId":"EXldyQ","dataJson":"Ljl9RA","fields":{"Challan No":"GGJazw","Date":"6vtDCw","Expiry":"xeL_7Q","Qty":"eyJxSA","Vehicle":"eqrHkg","Status":"XcJ-hg","POD":"2N131g","Customer":"h-kWoA","SKU":"cYB9fw","Batch":"w1VIww","Location":"u-o1OA","App ID":"EXldyQ","Data JSON":"Ljl9RA"}},
  "Stock Issues": {"name":"Stock Issues","id":"QnFYXg","appId":"bIK89w","dataJson":"HqPlTw","fields":{"Doc No":"QCnp1Q","Date":"owyssA","Reason":"YDV3yg","Issued To":"YtC7jw","Lines JSON":"cxSaaw","Value":"79BxDQ","App ID":"bIK89w","Data JSON":"HqPlTw"}},
  "Production Plans": {"name":"Production Plans","id":"Y3lkmQ","appId":"fzfBXQ","dataJson":"9UefBg","fields":{"Plan No":"BVgNew","Day":"16LLqw","Stage":"t6zjGQ","Product":"P8Iiyw","Qty":"7YEHrQ","UOM":"WEjuug","Note":"lGHXWA","Status":"Dr-b-A","App ID":"fzfBXQ","Data JSON":"9UefBg"}},
  "Shifts": {"name":"Shifts","id":"q1KHAA","appId":"AXshVg","dataJson":"2fVw3w","fields":{"Key":"kSfg0w","Date":"ePcSHA","Shift":"pSTwAg","Line":"iPdPkw","Note":"-S1pbQ","Staff":"Vng4zQ","App ID":"AXshVg","Data JSON":"2fVw3w"}},
  "Attendance": {"name":"Attendance","id":"7vMX8Q","appId":"eG67iQ","dataJson":"dAXIow","fields":{"Key":"3zdcuQ","Date":"Pa0JTg","Status":"aAcQeQ","Note":"f0F4Xg","Staff":"_r0Tug","App ID":"eG67iQ","Data JSON":"dAXIow"}},
  "Ledger": {"name":"Ledger","id":"r17sKQ","appId":"wvjocA","dataJson":"jRNMfg","fields":{"Doc":"G1BQmA","Type":"zCwGbA","Lot":"oMdXSQ","Status":"f8llFQ","Qty In":"aCdjfg","Qty Out":"29Flrg","Unit Cost":"eCX66w","Expiry":"UrKf5Q","Time":"Qz8axw","Data JSON":"jRNMfg","Item":"TyckWw","Location":"oBEz6w","App ID":"wvjocA"}},
  "Audit Log": {"name":"Audit Log","id":"JwjpIQ","appId":"S656ng","dataJson":"ay6fbg","fields":{"Doc":"OxrNnQ","Action":"QyRcww","Details":"h1-AaA","Actor":"Yso8yQ","Time":"JFSOPQ","App ID":"S656ng","Data JSON":"ay6fbg"}},
  "Sticker Templates": {"name":"Sticker Templates","id":"wUvRcw","appId":"QMqz2g","dataJson":"aLAsCQ","fields":{"Name":"MT3l2Q","Stage":"8no5PA","Template JSON":"w91cXg","App ID":"QMqz2g","Data JSON":"aLAsCQ"}},
  "Sticker Prints": {"name":"Sticker Prints","id":"1gipcg","appId":"YumHUw","dataJson":"ZjTelw","fields":{"Doc No":"hZ279A","Stage":"SUO-Ew","Title":"eDrNrA","Printed At":"TYbl7A","Qty":"1KQxtg","App ID":"YumHUw","Data JSON":"ZjTelw"}},
}

export const TABLE_FOR: Record<string, string> = {
  "vendor_types": "Vendor Types",
  "vendors": "Vendors",
  "customers": "Customers",
  "purchase_products": "Purchase Products",
  "storage_locations": "Storage Locations",
  "items": "Items",
  "products": "Products",
  "melanges": "Melanges",
  "grns": "GRNs",
  "batches": "Batches",
  "packing_runs": "Packing Runs",
  "orders": "Orders",
  "order_lines": "Order Lines",
  "qcs": "QC Records",
  "dispatches": "Dispatches",
  "stock_issues": "Stock Issues",
  "lab_reports": "Lab Reports",
  "test_parameters": "Test Parameters",
  "sticker_templates": "Sticker Templates",
  "sticker_prints": "Sticker Prints",
  "staff": "Staff",
  "shifts": "Shifts",
  "attendance": "Attendance",
  "production_plans": "Production Plans",
  "ledger": "Ledger",
  "audits": "Audit Log"
}
