// GENERATED by scripts/zoho/gen-base-schema.mjs — do not edit by hand.
// One entry per synced base; the active one is chosen by ZOHO_BASE_ID at import
// (DEFAULT_BASE_ID when unset), and a base nobody synced refuses to load — the
// multi-base answer to a half-done switch: local scratch and production deploy
// from the same committed file, and a mis-set ZOHO_BASE_ID fails at boot.
export interface TableRef {
  name: string
  id: string
  appId: string
  dataJson?: string
  fields: Record<string, string>
}

export const SCHEMAS: Record<string, Record<string, TableRef>> = {
  // synced from topup-state.dhorj90a.json
  "dhorj90a2ded0152a4f1d94ae8ce4ece09a5c": {
    "Vendor Types": {"name":"Vendor Types","id":"J8fAew","appId":"bIdD3Q","dataJson":"fihkzA","fields":{"Name":"mWDsTw","Source Kind":"d_SISg","Description":"OkAsRQ","Status":"e7N1Eg","Link to Vendors":"MHiaiA","App ID":"bIdD3Q","Data JSON":"fihkzA"}},
    "Vendors": {"name":"Vendors","id":"S6mCPQ","appId":"N7M87g","dataJson":"mUCm1A","fields":{"Name":"RsrjJQ","Phone":"IgaF2w","Area":"cTKTpQ","Payment Terms":"EuI4aQ","Status":"6Hsqrw","Email":"r1YVmw","Notes":"LSi-4Q","Vendor Type":"1HpEPw","Link to Purchase Products":"wMDCTA","Link to GRNs":"lGwzHQ","App ID":"N7M87g","Data JSON":"mUCm1A","Version":"Vc8igg"}},
    "Customers": {"name":"Customers","id":"Eyis7A","appId":"tVfd2w","dataJson":"d35BZw","fields":{"Name":"7Qkpvw","Ship To":"x3HFGg","GSTIN":"7hEZzA","Status":"qwdKoQ","Phone":"RGmwRg","Email":"xCjjeQ","Contact Person":"_gxAqA","Notes":"rpWUBQ","Link to Lab Reports":"6cfsXA","Link to Orders":"y3Fdkw","Link to Dispatches":"iUaqVw","App ID":"tVfd2w","Data JSON":"d35BZw","Version":"du1WKQ"}},
    "Items": {"name":"Items","id":"wbQrEQ","appId":"e_VT0Q","dataJson":"1mu_wg","fields":{"Name":"PpoqtQ","Type":"_BKnWg","UOM":"jd1Myg","Lot Controlled":"IyDQmA","Reorder Level":"SSAZ2Q","Cost Method":"9aOsEw","Link to Purchase Products":"p2moVQ","Link to Products":"p3tJkQ","Link to BOM Lines":"iYDDEA","Link to Melanges":"bMEblg","Link to Melange Components":"E4Em1Q","Link to Packing Runs":"rT3QHg","Link to QC Records":"NDfAlg","Link to Ledger":"B7WnUw","App ID":"e_VT0Q","Data JSON":"1mu_wg","Version":"DIWEug"}},
    "Purchase Products": {"name":"Purchase Products","id":"5ni6OA","appId":"Mr__lw","dataJson":"Txb5eQ","fields":{"Name":"3AD6-w","Default UOM":"MJ16Tg","Item":"3KSmNA","Linked Vendors":"3vPnXw","Link to GRNs":"x0DXcg","App ID":"Mr__lw","Data JSON":"Txb5eQ","Version":"KqcT2g"}},
    "Storage Locations": {"name":"Storage Locations","id":"YqOCjA","appId":"2PW1fg","dataJson":"n4PyuA","fields":{"Name":"sNsFpA","Label":"-9Xw5w","Holds":"TrEehw","Type":"rSm5Vw","Status":"ro-7oQ","Link to GRNs":"mfg58A","Link to Batches":"iXliRQ","Link to Packing Runs":"GNeEOQ","Link to Dispatches":"0oJhUg","Link to Ledger":"hJeLgw","App ID":"2PW1fg","Data JSON":"n4PyuA","Version":"tSPJaA"}},
    "Test Categories": {"name":"Test Categories","id":"VBvfXw","appId":"LeWJaQ","dataJson":"o0EOqA","fields":{"Title":"9tEHrw","Format":"Z7-yYg","Required for Release":"LJEe3A","Pass Score":"hr_xWg","Minor Score":"mzLgEQ","Signatory":"DtjfHA","Status":"YDOSNQ","Link to Test Parameters":"MuNBCg","Link to Lab Reports":"vcCk9w","App ID":"LeWJaQ","Data JSON":"o0EOqA"}},
    "Test Parameters": {"name":"Test Parameters","id":"QPV8cw","appId":"tsbi5g","dataJson":"jFBY_w","fields":{"Name":"p8lUhw","Method":"36Xc5g","Unit":"vPgdgg","Category":"nhKxWA","App ID":"tsbi5g","Data JSON":"jFBY_w","Version":"cgXbVg"}},
    "Products": {"name":"Products","id":"ffFn3w","appId":"h00iuA","dataJson":"YPalvg","fields":{"Name":"V8DP7g","Format":"-mYvFg","Size":"UBqqrg","Unit":"3l8bdQ","Pack Volume":"YbK3lw","Shelf Life Days":"aM43FQ","Chilled Shelf Life Days":"usFooQ","MRP":"mnFdTw","Medium":"KwUYQA","Bulk Item":"zduh7g","Link to BOM Lines":"TYwAAQ","Link to Order Lines":"oYLG6w","Link to Dispatches":"HGqyYQ","App ID":"h00iuA","Data JSON":"YPalvg","Version":"OEf6GQ"}},
    "BOM Lines": {"name":"BOM Lines","id":"jfdh2w","appId":"utmcmA","dataJson":"GRpj0A","fields":{"Line":"zfIZOg","Qty per Pack":"R-4XNA","Product":"4e3BDg","Item":"_RE51w","App ID":"utmcmA","Data JSON":"GRpj0A"}},
    "Melanges": {"name":"Melanges","id":"9ZBRBg","appId":"TxUAlA","dataJson":"NZs2pg","fields":{"Name":"MeS7ZQ","Status":"BcLplw","Output Item":"8y49VA","Link to Melange Components":"7n8WDg","App ID":"TxUAlA","Data JSON":"NZs2pg","Version":"ojMOsw"}},
    "Melange Components": {"name":"Melange Components","id":"2Yw3aw","appId":"YdSfiQ","dataJson":"W53o6A","fields":{"Line":"7ZKMiA","Share":"S5-StQ","Melange":"78C4JA","Item":"NpgT1A","App ID":"YdSfiQ","Data JSON":"W53o6A"}},
    "Counters": {"name":"Counters","id":"1l4Zyg","appId":"a4d7zA","fields":{"Series":"LsDPPA","Prefix":"pRhS8w","Pattern":"qP8tHA","Pad":"U8SH4g","Next":"FXa_pg","App ID":"a4d7zA"}},
    "Config": {"name":"Config","id":"_GPmew","appId":"zvpKQQ","fields":{"Setting":"gPjX7g","Value":"8KlOrg","Notes":"4ZYVyg","App ID":"zvpKQQ"}},
    "Staff": {"name":"Staff","id":"NhIr-w","appId":"1Y0FkQ","dataJson":"0UaM3g","fields":{"Staff No":"rOE8TQ","Name":"I9iRyA","Role":"iW0apg","Phone":"cKLfnQ","Status":"pwzEcw","Added On":"IYA94A","Link to Shifts":"6EtwEw","Link to Attendance":"4UdTuA","App ID":"1Y0FkQ","Data JSON":"0UaM3g","Version":"JG5xtg"}},
    "GRNs": {"name":"GRNs","id":"JWefYw","appId":"UnjJ3Q","dataJson":"yJdqrA","fields":{"Doc No":"sS7eYg","Date":"xa31Mw","UOM":"H5waRg","Area":"uRMmeA","Harvested On":"HrjCTA","Total":"LoCJ-g","Accepted":"WKnwyg","Free":"ZOcdSg","Grade A":"lEAVZg","Grade B":"rYt5fA","Grade C":"PEMOXQ","Reject":"SrFo5A","Rate":"MSb-kQ","Other Charges":"dqpepw","Status":"KACfAA","Notes":"XG_gxA","Product":"vSiTJA","Location":"BBTg8g","Vendor":"Yiy0mA","App ID":"UnjJ3Q","Data JSON":"yJdqrA","Version":"UNgZlg"}},
    "Batches": {"name":"Batches","id":"5ZkZOA","appId":"EqZmyA","dataJson":"ppf_Uw","fields":{"Batch No":"hlXcIg","Date":"_HXteA","Kind":"NMSTZw","Spoiled":"cjtEPQ","Cost per Unit":"qJi6Tg","Status":"afpPHA","Data JSON":"ppf_Uw","Location":"DhG6mw","Link to Packing Runs":"2V6Isw","Link to QC Records":"5Ee8ZA","Link to Lab Reports":"L4tueQ","Link to Dispatches":"Z6bnCw","App ID":"EqZmyA","Version":"m_xM8g"}},
    "Packing Runs": {"name":"Packing Runs","id":"aK0RyA","appId":"zYkg9A","dataJson":"r6uyyw","fields":{"Run No":"Nk6ucQ","Date":"FjAHyA","Drawn":"vV24Jg","Status":"M8eM0g","Data JSON":"r6uyyw","Batch":"XjQsbA","Bulk Item":"Q7WamQ","Location":"cvK-qQ","App ID":"zYkg9A","Version":"QvytWA"}},
    "QC Records": {"name":"QC Records","id":"FtR93w","appId":"2SFmmQ","dataJson":"IIcgIA","fields":{"Doc No":"qWOqhg","Disposition":"Tp2XxQ","Tests JSON":"dB6PSQ","Attachments":"tlwO8Q","Batch":"ZOJ5Xw","Item":"ULT4qg","App ID":"2SFmmQ","Data JSON":"IIcgIA","Version":"1RoERg"}},
    "Lab Reports": {"name":"Lab Reports","id":"1sbYJA","appId":"a2nt6g","dataJson":"Vg6SxA","fields":{"Report No":"XohvDA","Sample Date":"aO_TOQ","Issue Date":"PHqUGw","Scores JSON":"8OpJnw","Decision":"5uLRRA","Attachment":"o9TXJA","Category":"U9aWfw","Batch":"DkZjdg","Customer":"Zo7ggg","App ID":"a2nt6g","Data JSON":"Vg6SxA","Version":"TZa4xw"}},
    "Orders": {"name":"Orders","id":"-VGCAQ","appId":"kxYh8A","dataJson":"bBMaAQ","fields":{"Order No":"GenTxA","Date":"sJeFlA","Status":"psg9zw","Notes":"Y3YO0A","Customer":"enRipQ","Link to Order Lines":"jgFx5w","App ID":"kxYh8A","Data JSON":"bBMaAQ","Version":"HAQt8Q"}},
    "Order Lines": {"name":"Order Lines","id":"XF04qg","appId":"9Q8vcw","dataJson":"YEd52A","fields":{"Line":"6NlSpg","Qty":"zusIbQ","Order":"fH6cVg","SKU":"aevB4w","App ID":"9Q8vcw","Data JSON":"YEd52A"}},
    "Dispatches": {"name":"Dispatches","id":"tranOA","appId":"EXldyQ","dataJson":"Ljl9RA","fields":{"Challan No":"GGJazw","Date":"6vtDCw","Expiry":"xeL_7Q","Qty":"eyJxSA","Vehicle":"eqrHkg","Status":"XcJ-hg","POD":"2N131g","Customer":"h-kWoA","SKU":"cYB9fw","Batch":"w1VIww","Location":"u-o1OA","App ID":"EXldyQ","Data JSON":"Ljl9RA","Version":"GtfViA"}},
    "Stock Issues": {"name":"Stock Issues","id":"QnFYXg","appId":"bIK89w","dataJson":"HqPlTw","fields":{"Doc No":"QCnp1Q","Date":"owyssA","Reason":"YDV3yg","Issued To":"YtC7jw","Lines JSON":"cxSaaw","Value":"79BxDQ","App ID":"bIK89w","Data JSON":"HqPlTw","Version":"8rFzEQ"}},
    "Production Plans": {"name":"Production Plans","id":"Y3lkmQ","appId":"fzfBXQ","dataJson":"9UefBg","fields":{"Plan No":"BVgNew","Day":"16LLqw","Stage":"t6zjGQ","Product":"P8Iiyw","Qty":"7YEHrQ","UOM":"WEjuug","Note":"lGHXWA","Status":"Dr-b-A","App ID":"fzfBXQ","Data JSON":"9UefBg","Version":"XmfhQg"}},
    "Shifts": {"name":"Shifts","id":"q1KHAA","appId":"AXshVg","dataJson":"2fVw3w","fields":{"Key":"kSfg0w","Date":"ePcSHA","Shift":"pSTwAg","Line":"iPdPkw","Note":"-S1pbQ","Staff":"Vng4zQ","App ID":"AXshVg","Data JSON":"2fVw3w","Version":"QdK20Q"}},
    "Attendance": {"name":"Attendance","id":"7vMX8Q","appId":"eG67iQ","dataJson":"dAXIow","fields":{"Key":"3zdcuQ","Date":"Pa0JTg","Status":"aAcQeQ","Note":"f0F4Xg","Staff":"_r0Tug","App ID":"eG67iQ","Data JSON":"dAXIow","Version":"YnP1Aw"}},
    "Ledger": {"name":"Ledger","id":"r17sKQ","appId":"wvjocA","dataJson":"jRNMfg","fields":{"Doc":"G1BQmA","Type":"zCwGbA","Lot":"oMdXSQ","Status":"f8llFQ","Qty In":"aCdjfg","Qty Out":"29Flrg","Unit Cost":"eCX66w","Expiry":"UrKf5Q","Time":"Qz8axw","Data JSON":"jRNMfg","Item":"TyckWw","Location":"oBEz6w","App ID":"wvjocA"}},
    "Audit Log": {"name":"Audit Log","id":"JwjpIQ","appId":"S656ng","dataJson":"ay6fbg","fields":{"Doc":"OxrNnQ","Action":"QyRcww","Details":"h1-AaA","Actor":"Yso8yQ","Time":"JFSOPQ","App ID":"S656ng","Data JSON":"ay6fbg"}},
    "Sticker Templates": {"name":"Sticker Templates","id":"wUvRcw","appId":"QMqz2g","dataJson":"aLAsCQ","fields":{"Name":"MT3l2Q","Stage":"8no5PA","Template JSON":"w91cXg","App ID":"QMqz2g","Data JSON":"aLAsCQ","Version":"v66iYA"}},
    "Sticker Prints": {"name":"Sticker Prints","id":"1gipcg","appId":"YumHUw","dataJson":"ZjTelw","fields":{"Doc No":"hZ279A","Stage":"SUO-Ew","Title":"eDrNrA","Printed At":"TYbl7A","Qty":"1KQxtg","App ID":"YumHUw","Data JSON":"ZjTelw"}},
    "Compliance Documents": {"name":"Compliance Documents","id":"skl6qw","appId":"B--Q2Q","dataJson":"oAc1zg","fields":{"Title":"8mhywA","Expires On":"m_GWmg","Version":"1ixbTQ","App ID":"B--Q2Q","Data JSON":"oAc1zg"}},
  },
  // synced from topup-state.gerc53fe.json
  "gerc53fe9f1e44e5f4a13809d9bd47367ba9d": {
    "Vendor Types": {"name":"Vendor Types","id":"Q51KfQ","appId":"SgQ1tA","dataJson":"z2XJCg","fields":{"Name":"RL55hQ","Source Kind":"eOYZug","Description":"aDofuw","Status":"iMG4UA","Link to Vendors":"M7YYig","App ID":"SgQ1tA","Data JSON":"z2XJCg"}},
    "Vendors": {"name":"Vendors","id":"emPb1Q","appId":"UaDEwA","dataJson":"_T-lIw","fields":{"Name":"04uhjg","Phone":"_hmL6A","Area":"RxTCGw","Payment Terms":"d_VTlw","Status":"MYyIYQ","Email":"i6_-sQ","Notes":"9B6uxQ","Vendor Type":"f6eWVA","Link to Purchase Products":"b_QTKA","Link to GRNs":"T7-2Pg","App ID":"UaDEwA","Data JSON":"_T-lIw","Version":"kSPPdw"}},
    "Customers": {"name":"Customers","id":"uq7Lag","appId":"qsgI8g","dataJson":"r81F0w","fields":{"Name":"rXuTTA","Ship To":"8r5wrg","GSTIN":"KlHKKA","Status":"SaKg-w","Phone":"EBqtDg","Email":"m2fbUQ","Contact Person":"kBb5ow","Notes":"CQmW2Q","Link to Lab Reports":"lmAA_Q","Link to Orders":"vfRK5Q","Link to Dispatches":"tJC3Gw","App ID":"qsgI8g","Data JSON":"r81F0w","Version":"GSSBpA"}},
    "Items": {"name":"Items","id":"-pn8Rg","appId":"qke45w","dataJson":"LX8o0g","fields":{"Name":"PPC3zw","Type":"fDbxMQ","UOM":"ZYWKcg","Lot Controlled":"taWNSw","Reorder Level":"nPXgUg","Cost Method":"8b5QaQ","Link to Purchase Products":"zVj6MA","Link to Products":"GZ3tJw","Link to BOM Lines":"fM9dvg","Link to Melanges":"_ApGaw","Link to Melange Components":"VTlA8g","Link to Packing Runs":"HXzf4A","Link to QC Records":"Ec8KUw","Link to Ledger":"CKyaLg","App ID":"qke45w","Data JSON":"LX8o0g","Version":"vWoRfA"}},
    "Purchase Products": {"name":"Purchase Products","id":"j937WA","appId":"KX8vQA","dataJson":"dBd9eg","fields":{"Name":"2MjAAA","Default UOM":"5V_gAQ","Item":"203N1A","Linked Vendors":"oP1slA","Link to GRNs":"7mM5Ig","App ID":"KX8vQA","Data JSON":"dBd9eg","Version":"qi0QZA"}},
    "Storage Locations": {"name":"Storage Locations","id":"eU3gew","appId":"mqCiIA","dataJson":"fWL1JA","fields":{"Name":"Fbdl9w","Label":"6QTydg","Holds":"YfR-Ng","Type":"Mo383Q","Status":"_ikJig","Link to GRNs":"E3vV9A","Link to Batches":"mZA5Ww","Link to Packing Runs":"2WgAvQ","Link to Dispatches":"ARfHVw","Link to Ledger":"TVNgFQ","App ID":"mqCiIA","Data JSON":"fWL1JA","Version":"z09rMg"}},
    "Test Categories": {"name":"Test Categories","id":"4U0lqg","appId":"lKZrqA","dataJson":"1y01nA","fields":{"Title":"IN88Vg","Format":"UdSLBQ","Required for Release":"rjN7Cg","Pass Score":"iguVZg","Minor Score":"hMuX6w","Signatory":"FKCE7Q","Status":"jQyGmw","Link to Test Parameters":"c9IBEw","Link to Lab Reports":"WsXb7A","App ID":"lKZrqA","Data JSON":"1y01nA"}},
    "Test Parameters": {"name":"Test Parameters","id":"hBvaNA","appId":"2hHeeg","dataJson":"nUJ91A","fields":{"Name":"Jo7nGQ","Method":"RS4gkA","Unit":"ve9YZQ","Category":"LwwoFw","App ID":"2hHeeg","Data JSON":"nUJ91A","Version":"Zjf5GQ"}},
    "Products": {"name":"Products","id":"wtZplw","appId":"efKp5w","dataJson":"T6oulA","fields":{"Name":"R84ItA","Format":"i0jfDQ","Size":"_aK5Lg","Unit":"JbsGxA","Pack Volume":"A2e6JA","Shelf Life Days":"TYw0lg","Chilled Shelf Life Days":"HRHNQw","MRP":"ao_uIg","Medium":"LX9yXA","Bulk Item":"8Q5QNg","Link to BOM Lines":"QC27-w","Link to Order Lines":"RgIh4A","Link to Dispatches":"NBxqAA","App ID":"efKp5w","Data JSON":"T6oulA","Version":"CY_stA"}},
    "BOM Lines": {"name":"BOM Lines","id":"_BMFqw","appId":"kEKUaA","dataJson":"T25HMg","fields":{"Line":"HaG3HQ","Qty per Pack":"_ZiaEg","Product":"X8OAEw","Item":"J9lLLQ","App ID":"kEKUaA","Data JSON":"T25HMg"}},
    "Melanges": {"name":"Melanges","id":"HxQjjQ","appId":"jvYqGQ","dataJson":"zUeZLQ","fields":{"Name":"ywkOcw","Status":"qQx6Jg","Output Item":"iXRk5A","Link to Melange Components":"G6s0Uw","App ID":"jvYqGQ","Data JSON":"zUeZLQ","Version":"Wiw8AQ"}},
    "Melange Components": {"name":"Melange Components","id":"eDbSvg","appId":"wlTLQg","dataJson":"WRM37g","fields":{"Line":"NcmTiw","Share":"-NXEbQ","Melange":"Oh5T5A","Item":"_JfkNw","App ID":"wlTLQg","Data JSON":"WRM37g"}},
    "Counters": {"name":"Counters","id":"la-DXQ","appId":"JCXZPA","fields":{"Series":"NlaXqg","Prefix":"TQXrSw","Pattern":"NgfLVg","Pad":"R9OwRw","Next":"SabsYg","App ID":"JCXZPA"}},
    "Config": {"name":"Config","id":"0jAjUQ","appId":"YzXOxA","fields":{"Setting":"batStA","Value":"WcDTZQ","Notes":"GM8CUg","App ID":"YzXOxA"}},
    "Staff": {"name":"Staff","id":"-7_2Lw","appId":"IYd3fA","dataJson":"CAsnww","fields":{"Staff No":"mKGDbQ","Name":"MSPtUA","Role":"SvWaiw","Phone":"4kjuow","Status":"ZwCzNQ","Added On":"HB5G_Q","Link to Shifts":"BhGKSA","Link to Attendance":"z07PIw","App ID":"IYd3fA","Data JSON":"CAsnww","Version":"8xcMbA"}},
    "GRNs": {"name":"GRNs","id":"zYc_3A","appId":"GweH5w","dataJson":"I4as_w","fields":{"Doc No":"mpuNTw","Date":"tZMtQA","UOM":"5yAcKg","Area":"n1Upgg","Harvested On":"B3gZhw","Total":"jnuzPw","Accepted":"tBSfBw","Free":"uRm70g","Grade A":"LmBRqg","Grade B":"n5c3ig","Grade C":"mMWFNA","Reject":"2nbJkQ","Rate":"eLB1gQ","Other Charges":"Epkb8A","Status":"8B9oGw","Notes":"XuWNDg","Product":"Xcb2lQ","Location":"ksCnhQ","Vendor":"tG3byA","App ID":"GweH5w","Data JSON":"I4as_w","Version":"ifsvOw"}},
    "Batches": {"name":"Batches","id":"zYKaHQ","appId":"EPz9ig","dataJson":"Z3iOkg","fields":{"Batch No":"SNbqHw","Date":"M3XoOA","Kind":"sGas1w","Spoiled":"-wO95A","Cost per Unit":"D6eCXA","Status":"ahgEMQ","Data JSON":"Z3iOkg","Location":"772fnw","Link to Packing Runs":"JE-4Sg","Link to QC Records":"dXy3Kg","Link to Lab Reports":"Wal1kQ","Link to Dispatches":"BehC2Q","App ID":"EPz9ig","Version":"NizliA"}},
    "Packing Runs": {"name":"Packing Runs","id":"UiOExg","appId":"N_2vRA","dataJson":"wrDPVQ","fields":{"Run No":"ta6pPw","Date":"XzOTag","Drawn":"JooyRg","Status":"gNpRNg","Data JSON":"wrDPVQ","Batch":"muIYuA","Bulk Item":"JKMIyw","Location":"8Ka4_w","App ID":"N_2vRA","Version":"uAtgtQ"}},
    "QC Records": {"name":"QC Records","id":"bnL8sQ","appId":"slMbXA","dataJson":"SE_fog","fields":{"Doc No":"Psi57w","Disposition":"3JtFig","Tests JSON":"m02Ymw","Attachments":"Rvm7QQ","Batch":"5a85Nw","Item":"lntI1Q","App ID":"slMbXA","Data JSON":"SE_fog","Version":"VFwyyQ"}},
    "Lab Reports": {"name":"Lab Reports","id":"6KPiJg","appId":"BMiOtQ","dataJson":"8jNTfA","fields":{"Report No":"6VOBSA","Sample Date":"r1h8Vw","Issue Date":"qWabHQ","Scores JSON":"VSc8Hg","Decision":"FcMUjg","Attachment":"5pGvYw","Category":"rNtGjg","Batch":"OaFgbw","Customer":"wmWZpw","App ID":"BMiOtQ","Data JSON":"8jNTfA","Version":"rsigsA"}},
    "Orders": {"name":"Orders","id":"faITbA","appId":"p_08eQ","dataJson":"LZuEiw","fields":{"Order No":"eK3rpw","Date":"SxaYSw","Status":"HCGtCA","Notes":"AHaJkQ","Customer":"IYIjIA","Link to Order Lines":"c5HBhA","App ID":"p_08eQ","Data JSON":"LZuEiw","Version":"TrptDg"}},
    "Order Lines": {"name":"Order Lines","id":"NfaemA","appId":"g52kkw","dataJson":"tZ-4Vg","fields":{"Line":"Pc0AxA","Qty":"SflKkw","Order":"dZYIyg","SKU":"nZTjuQ","App ID":"g52kkw","Data JSON":"tZ-4Vg"}},
    "Dispatches": {"name":"Dispatches","id":"WwwsFQ","appId":"djjBXw","dataJson":"sdKCxA","fields":{"Challan No":"F6Q_AQ","Date":"3OLwcw","Expiry":"RKgphA","Qty":"3FedPg","Vehicle":"nDxKiw","Status":"osN62w","POD":"X9oQqQ","Customer":"tLTqzQ","SKU":"UEbucA","Batch":"IFO-lw","Location":"WgAK7A","App ID":"djjBXw","Data JSON":"sdKCxA","Version":"yrlX-Q"}},
    "Stock Issues": {"name":"Stock Issues","id":"gFa2tg","appId":"s5-0SQ","dataJson":"dnfDaA","fields":{"Doc No":"pXisDw","Date":"jwwpwg","Reason":"wR16KA","Issued To":"Z2sN9Q","Lines JSON":"xrHNLQ","Value":"twCHUQ","App ID":"s5-0SQ","Data JSON":"dnfDaA","Version":"oZjEyg"}},
    "Production Plans": {"name":"Production Plans","id":"_FPGJw","appId":"AB76aA","dataJson":"J-eCMQ","fields":{"Plan No":"oG-tMQ","Day":"aKU7tw","Stage":"1vfDmQ","Product":"o5HFSg","Qty":"UCPu2w","UOM":"yK5rAA","Note":"phNpmw","Status":"R8_qzg","App ID":"AB76aA","Data JSON":"J-eCMQ","Version":"YRZmwg"}},
    "Shifts": {"name":"Shifts","id":"FjRdFA","appId":"lvVCUg","dataJson":"sC6JFg","fields":{"Key":"eWXQ-w","Date":"3lR-qw","Shift":"pIup2g","Line":"VbNidQ","Note":"m7dM1A","Staff":"zDYSmA","App ID":"lvVCUg","Data JSON":"sC6JFg","Version":"HlzkYQ"}},
    "Attendance": {"name":"Attendance","id":"NCe8vQ","appId":"ODvEdQ","dataJson":"npIR2Q","fields":{"Key":"V1998Q","Date":"SZQqAQ","Status":"F4YsSg","Note":"jeyxPg","Staff":"iMUGGw","App ID":"ODvEdQ","Data JSON":"npIR2Q","Version":"0Df0VA"}},
    "Ledger": {"name":"Ledger","id":"TUf1EA","appId":"PAze8Q","dataJson":"XnQjTw","fields":{"Doc":"ISSAjA","Type":"tF3wKw","Lot":"LLKIHg","Status":"sE5dZA","Qty In":"Rc-sSA","Qty Out":"a3roIQ","Unit Cost":"1SVG0Q","Expiry":"Hi-K0Q","Time":"ZyVR8Q","Data JSON":"XnQjTw","Item":"H14YGQ","Location":"gAC7Qw","App ID":"PAze8Q"}},
    "Audit Log": {"name":"Audit Log","id":"Ozntnw","appId":"CwW9iA","dataJson":"SZ4XtA","fields":{"Doc":"x-XwPg","Action":"fv2PTw","Details":"df8NMA","Actor":"u7pGxA","Time":"dZucpg","App ID":"CwW9iA","Data JSON":"SZ4XtA"}},
    "Sticker Templates": {"name":"Sticker Templates","id":"9wnUOg","appId":"iejL6w","dataJson":"0pTdIw","fields":{"Name":"TtX0xw","Stage":"aJlcLg","Template JSON":"92YhGA","App ID":"iejL6w","Data JSON":"0pTdIw","Version":"JfyzJg"}},
    "Sticker Prints": {"name":"Sticker Prints","id":"RbDZBw","appId":"FzJY-A","dataJson":"cY4MdQ","fields":{"Doc No":"3YudaA","Stage":"NYBYNQ","Title":"BZlg9A","Printed At":"VLtdnQ","Qty":"Hvy63Q","App ID":"FzJY-A","Data JSON":"cY4MdQ"}},
  },
}

export const DEFAULT_BASE_ID = "dhorj90a2ded0152a4f1d94ae8ce4ece09a5c"

export const TABLE_FOR: Record<string, string> = {
  "vendor_types": "Vendor Types",
  "vendors": "Vendors",
  "customers": "Customers",
  "purchase_products": "Purchase Products",
  "storage_locations": "Storage Locations",
  "items": "Items",
  "products": "Products",
  "melanges": "Melanges",
  "grns": "GRNs",
  "batches": "Batches",
  "packing_runs": "Packing Runs",
  "orders": "Orders",
  "order_lines": "Order Lines",
  "qcs": "QC Records",
  "dispatches": "Dispatches",
  "stock_issues": "Stock Issues",
  "lab_reports": "Lab Reports",
  "test_parameters": "Test Parameters",
  "sticker_templates": "Sticker Templates",
  "sticker_prints": "Sticker Prints",
  "staff": "Staff",
  "shifts": "Shifts",
  "attendance": "Attendance",
  "production_plans": "Production Plans",
  "ledger": "Ledger",
  "audits": "Audit Log"
}

/**
 * The tables of the named base. Unset falls back to DEFAULT_BASE_ID — the base
 * this checkout was generated against, and the world tests run in; a base with
 * no synced state throws rather than guess, naming what to run.
 */
export function schemaFor(baseId?: string | undefined): Record<string, TableRef> {
  const id = baseId || DEFAULT_BASE_ID
  const tables = SCHEMAS[id]
  if (!tables) {
    throw new Error(
      'no generated schema for base ' + id + ' (have: ' + Object.keys(SCHEMAS).join(', ') + ')' +
        ' — sync it first (node scripts/zoho/topup.mjs ' + id + '), which regenerates this file',
    )
  }
  return tables
}

export const T = schemaFor(process.env.ZOHO_BASE_ID)
